const MILLION = 1000000
const BILLION = 1000000000

const companyEmissionsPerRevenue = {
    "Apple":[25.1*MILLION/(260.17*BILLION), 'USD', [1,2], 2019],  // 25.1M mtc02 in 2019, $260.17 revenue for 2019
    "Royal Dutch Shell": [  ((63+9+1305)*MILLION)/ (180543*MILLION), 'USD', [1,2,3], 2020], // scope 1, 2,3 and $180543 2020
    "BP": [ ((55+361)*MILLION)/(278397*MILLION), 'USD', [1,2,3], 2019],
    "Volkswagen": [((3.77+7.57+447.420740)*MILLION)/(252.63*BILLION)), 'EUR', [1,2,3], 2019 ],
    "Vitol Group": [(1000445+282152)/(140*BILLION), 'USD',[1,2], 2020],
    "Glencore": [],
    "Total": [],
    "Daimler": [],
    "Exor": [],
    "Allianz": [],
    "Gazprom": [],
    "AXA": [],
    "Carrefour": [],
    "Eni": [],
    "Engie": [],
    "BNP Paribas": [],
    "E.ON": [],
    "ING": [],
    "Equinor": [],
    "Banco Santander": [],
    "FCA Group": [],
    "Siemens": [],
    "Assicurazioni Generali": [],
    "Lukoil": [],
    "Enel": [],
    "HSBC": [],
    "Crédit Agricole": [],
    "Tesco": [],
    "BASF": [],
    "Société Générale": [],
    "BMW": [],
    "ArcelorMittal": [],
    "Nestlé": [],
    "Metro": [],
    "Électricité de France": [],
    "Munich Re": [],
    "Telefónica": [],
    "Bosch": [],
    "Groupe PSA": [],
    "Deutsche Telekom": [],
    "Repsol": [],
    "Deutsche Post": [],
    "Groupe BPCE": [],
    "Deutsche Bank": [],
    "Vodafone": [],
    "Barclays": [],
    "ThyssenKrupp": [],
    "RWE": [],
    "Airbus SE": [],
    "Lloyds Banking Group": [],
    "Rosneft": [],
    "Unilever": [],
    "Hoffmann-La Roche": [],
    "Orange": [],
    "NatWest Group": [],
    "Ahold Delhaize": [],
    "Aviva": [],
    "Auchan": [],
    "Rio Tinto Group": [],
    "Maersk": [],
    "Novartis": [],
    "Renault": [],
    "Saint-Gobain": [],
    "Prudential": [],
    "UniCredit": [],
    "Nokia": [],
    "Zurich Insurance Group": [],
    "Deutsche Bahn": [],
    "CNP Assurances": [],
    "Vinci": [],
    "LyondellBasell": [],
    "Banco Bilbao Vizcaya Argentaria": [],
    "SSE": [],
    "Bayer": [],
    "Intesa Sanpaolo": [],
    "Groupe Casino": [],
    "Sanofi": [],
    "Veolia Environnement": [],
    "Credit Suisse": [],
    "Volvo": [],
    "OMV": [],
    "UBS": [],
    "Bouygues": [],
    "SNCF": [],
    "Aegon": [],
    "Iberdrola": [],
    "GlaxoSmithKline": [],
    "Grupo ACS": [],
    "Continental": [],
    "Telecom Italia": [],
    "Lufthansa": [],
    "Vivendi": [],
    "Anheuser-Busch InBev": [],
    "Franz Haniel & Cie.": [],
    "ABB": [],
    "Alliance Boots": [],
    "Rabobank Group": [],
    "Centrica": [],
    "Heraeus": [],
    "PKN Orlen": [],
    "Sainsbury's": [],
    "Sberbank": [],
    "Philips": [],
    "Ericsson": [],
    "Sistema": [],
    "La Poste": [],
    "Christian Dior": [],
    "Air France-KLM": [],
    "AstraZeneca": [],
    "DZ Bank": [],
    "Ineos": [],
    "Edeka": [],
    "Schneider Electric": [],
    "BT Group": [],
    "Anglo American": [],
    "Poste italiane": [],
    "Phoenix Pharmahandel": [],
    "Coop": [],
    "Legal & General": [],
    "GasTerra": [],
    "Naturgy": [],
    "Mapfre": [],
    "Michelin": [],
    "BAE Systems": [],
    "Adecco": [],
    "Dexia": [],
    "L'Oréal": [],
    "Morrisons": [],
    "Swiss Re": [],
    "Migros": [],
    "Vattenfall": [],
    "Alstom": [],
    "Accenture": [],
    "Groupe Danone": [],
    "MOL Group": [],
    "EnBW": [],
    "KBC Bank": [],
    "Surgutneftegas": [],
    "Compass Group": [],
    "Achmea": [],
    "CRH": [],
    "Leonardo-Finmeccanica": [],
    "Unipol": [],
    "British American Tobacco": [],
    "Standard Chartered": [],
    "Imperial Tobacco": [],
    "TUI Travel": [],
    "Marquard & Bahls": [],=
    "SHV Holdings": [],
    "Heineken": [],
    "Holcim": [],
    "Nordea": [],
    "Fresenius": [],
    "Lafarge": [],
    "Randstad Holding": [],
    "KfW": [],
    "Bertelsmann": [],
    "International Airlines Group": [],
    "Sodexo": [],
    "National Grid": [],

}


module.exports = companyEmissionsPerRevenue