const spendingEmissionsFactorsUKgovGBP = require('./spendingEmissionsFactorsUKgovGBP')
const emissionsCarbonFootprintOrgGBP = require('./emissionsCarbonFootprintOrgGBP')
const USAspendingEmissionsFactors = require('./USAspendingEmissionsFactors')

const mccEmissionsFactors = {
    "Veterinary Services": spendingEmissionsFactorsUKgovGBP["Veterinary services"],
    "Agricultural Co-operatives":spendingEmissionsFactorsUKgovGBP["Agriculture products"],
    "Horticultural Services":spendingEmissionsFactorsUKgovGBP["Agriculture products"],
    "Landscaping Services":spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "General Contractors-Residential and Commercial": spendingEmissionsFactorsUKgovGBP["Real estate services. excluding on a fee or contract basis and imputed rent"],
    "Air Conditioning Contractors – Sales and Installation": spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Heating Contractors – Sales, Service, Installation":spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Electrical Contractors": spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Insulation – Contractors":spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "Masonry, Stonework Contractors":spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "Plastering Contractors":spendingEmissionsFactorsUKgovGBP["Rubber and plastic products"],
    "Stonework and Masonry Contractors":spendingEmissionsFactorsUKgovGBP["Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products"],
    "Tile Settings Contractors":spendingEmissionsFactorsUKgovGBP["Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products"],
    "Carpentry Contractors":spendingEmissionsFactorsUKgovGBP["Wood and wood products"],
    "Roofing - Contractors": spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "Sheet Metal Work - Contractors":spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "Siding - Contractors":spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "Contractors – Concrete Work":spendingEmissionsFactorsUKgovGBP["Manufacture of cement. lime. plaster and articles of concrete. cement and plaster"],
    "Contractors – Special Trade, Not Elsewhere Classified":spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "Miscellaneous Publishing and Printing":spendingEmissionsFactorsUKgovGBP["Publishing services"],
    "Typesetting, Plate Making, & Related Services":spendingEmissionsFactorsUKgovGBP["Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products"],
    "Specialty Cleaning, Polishing, and Sanitation Preparations":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "UNITED AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AMERICAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "PAN AMERICAN":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TRANS WORLD AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BRITISH AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "JAPAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR FRANCE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LUFTHANSA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR CANADA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "KLM (ROYAL DUTCH AIRLINES)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AEORFLOT":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "QUANTAS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ALITALIA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SAUDIA ARABIAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SWISSAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SAS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SOUTH AFRICAN AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "VARIG (BRAZIL)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR-INDIA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR ALGERIE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "PHILIPPINE AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "MEXICANA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "PAKISTAN INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR NEW ZEALAND":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "UTA/INTERAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR MALTA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SABENA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AEROLINEAS ARGENTINAS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "OLYMPIC AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "EL AL":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ANSETT AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AUSTRAINLIAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TAP (PORTUGAL)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "VASP (BRAZIL)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "EGYPTAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "KUWAIT AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AVIANCA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "GULF AIR (BAHRAIN)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BALKAN-BULGARIAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "FINNAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AER LINGUS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR LANKA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "NIGERIA AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CRUZEIRO DO SUL (BRAZIJ)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "THY (TURKEY)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ROYAL AIR MAROC":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TUNIS AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ICELANDAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AUSTRIAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LANCHILE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AVIACO (SPAIN)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LADECO (CHILE)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LAB (BOLIVIA)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "QUEBECAIRE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "EASTWEST AIRLINES (AUSTRALIA)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "DELTA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "NORTHWEST":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CONTINENTAL":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "WESTERN":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "US AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIRINTER":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SOUTHWEST":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR BRITISH COLUBIA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SINGAPORE AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AEROMEXICO":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "THAI AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CHINA AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "NORDAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "KOREAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR AFRIGUE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "EVA AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "MIDWEST EXPRESS AIRLINESspending": spendingEmissionsFactorsUKgovGBP["Air transport"],
    "INC.":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "METRO AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CROATIA AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TRANSAERO":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ZAMBIA AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR ZIMBABWE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CATHAY PACIFIC":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "MALAYSIAN AIRLINE SYSTEM":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "IBERIA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "GARUDA (INDONESIA)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BRAATHENS S.A.F.E. (NORWAY)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "WINGS AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BRITISH MIDLAND":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "WINDWARD ISLAND":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "VIASA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "VALLEY AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TAN":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TALAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TACA INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SURINAM AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SUN WORLD INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SUNBELT AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SUDAN AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SINGLETON":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SIMMONS AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SCENIC AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "VIRGIN ATLANTIC":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SAN JUAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LUXAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR ZAIRE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "PRINCEVILLE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "PBA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ALL NIPPON AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "NORONTAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "NEW YORK HELICOPTER":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "NOUNT COOK":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CANADIAN AIRLINES INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "NATIONAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "METROFLIGHT AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "MESA AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "MALEV":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LOT (POLAND)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LIAT":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LAV (VENEZUELA)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LAP (PARAGUAY)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "LACSA (COSTA RICA)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "JUGOSLAV AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ISLAND AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "IRAN AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "INDIAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "HAWAIIAN AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "HAVASU AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "FUYANA AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "GOLDEN PACIFIC AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "FREEDOM AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "DOMINICANA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "DAN AIR SERVICES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CUMBERLAND AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CSA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CROWN AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "COPA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "COMPANIA FAUCETT":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TRANSPORTES AEROS MILITARES ECCUATORANOS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "COMMAND AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "COMAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CAYMAN AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SAETA SOCIAEDAD ECUATORIANOS DE TRANSPORTES AEREOS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "SASHA SERVICIO AERO DE HONDURAS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CAPITOL AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BWIA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BROKWAY AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BEMIDJI AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BAR HARBOR AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "BAHAMASAIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AVIATECA (GUATEMALA)":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AVENSA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AUSTRIAN AIR SERVICE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ALOHA AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ALM":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AMERICA WEST":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "TRUMP AIRLINE":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ALASKA AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AMERICAN TRANS AIR":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR CHINA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "RENO AIR": spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR SEYCHELLES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR PANAMA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR JAMAICA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR DJIBOUTI":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AERO VIRGIN ISLANDS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AERO PERU":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AEROLINEAS NICARAGUENSIS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AERO COACH AVAIATION":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ARIANA AFGHAN":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "CYPRUS AIRWAYS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ECUATORIANA":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "ETHIOPIAN AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "KENYA AIRLINES":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AIR MAURITIUS":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "WIDERO’S FLYVESELSKAP":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "AFFILIATED AUTO RENTAL":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AMERICAN INTL RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "BROOKS RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ACTION AUTO RENTAL":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "HERTZ RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "PAYLESS CAR RENTAL":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "SNAPPY CAR RENTAL":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AIRWAYS RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ALTRA AUTO RENTAL":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AGENCY RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "BUDGET RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "HOLIDAY RENT-A-WRECK":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "RENT-A-WRECK":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AJAX RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "EUROP CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "TROPICAL RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "SHOWCASE RENTAL CARS":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ALAMO RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AVIS RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "DOLLAR RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "EUROPE BY CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "NATIONAL CAR RENTAL":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "KEMWELL GROUP RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "THRIFTY RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "TILDEN TENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ECONO-CAR RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AUTO HOST COST CAR RENTALS":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ENTERPRISE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "GENERAL RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "A-1 RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "GODFREY NATL RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ALPHA RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ANSA INTL RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "ALLSTAE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AVCAR RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AUTOMATE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AVON RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "CAREY RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "INSURANCE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "MAJOR RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "REPLACEMENT RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "RESERVE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "UGLY DUCKLING RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "USA RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "VALUE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "AUTOHANSA RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "CITE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "INTERENT RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "MILLEVILLE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "VIA ROUTE RENT-A-CAR":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "HOLIDAY INN EXPRESS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOLIDAY INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "BEST WESTERN HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SHERATON HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HILTON HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FORTE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "GOLDEN TULIP HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FRIENDSHIP INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "QUALITY INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "QUALITY SUITES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MARRIOTT HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DAYS INN":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DAYSTOP":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ARABELLA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "INTER-CONTINENTAL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "WESTIN HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RODEWAY INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "LA QUINTA MOTOR INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "AMERICANA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SOL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PULLMAN INTERNATIONAL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MERIDIEN HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CREST HOTELS (see FORTE HOTELS)":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "TOKYO HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PENNSULA HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "WELCOMGROUP HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DUNFEY HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PRINCE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DOWNTOWNER-PASSPORT HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RED LION HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RED LION INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CP HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RENAISSANCE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "STOUFFER HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ASTIR HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SUN ROUTE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOTEL IBIS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SOUTHERN PACIFIC HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HILTON INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "AMFAC HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ANA HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CONCORDE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "IBEROTEL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOTEL OKURA":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ROYAL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FOUR SEASONS HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CIGA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SHANGRI-LA INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOTELES MELIA":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "AUBERGE DES GOVERNEURS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "REGAL 8 INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "COAST HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PARK INNS INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "JOLLY HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "COMFORT INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "JOURNEY’S END MOTLS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RELAX INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "LADBROKE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FORUM HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MIYAKO HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SANDMAN HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "VENTURE INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "VAGABOND HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MANDARIN ORIENTAL HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOTEL MERCURE":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DELTA HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SAS HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PRINCESS HOTELS INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HUNGAR HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SOKOS HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DORAL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HELMSLEY HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FAIRMONT HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SONESTA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "OMNI HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CUNARD HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOSPITALITY INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "REGENT INTERNATIONAL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PANNONIA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "NOAH’S HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MOVENPICK HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "TRAVELODGE":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "TELFORD INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MERLIN HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DORINT HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOTLE UNIVERSALE":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DAN HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RANK HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SWISSOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RESO HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SAROVA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RAMADA INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RAMADA LIMITED":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HO JO INN":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOWARD JOHNSON":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MOUNT CHARLOTTE THISTLE":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HYATT HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SOFITEL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "NOVOTEL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "STEIGENBERGER HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ECONO LODGES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "QUEENS MOAT HOUSES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SWALLOW HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HUSA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DE VERE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RADISSON HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RED ROOK INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "IMPERIAL LONDON HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "EMBASSY HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PENTA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "LOEWS HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SCANDIC HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SARA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "OBEROI HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "OTANI HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "TAJ HOTELS INTERNATIONAL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "KNIGHTS INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "METROPOLE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOTELES EL PRESIDENTS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FLAG INN":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HAMPTON INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "STAKIS HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MARITIM HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ARCARD HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ARCTIA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CAMPANIEL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "IBUSZ HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RANTASIPI HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "INTERHOTEL CEDOK":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CLIMAT DE FRANCE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CUMULUS HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DANUBIUS HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ADAMS MARK HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ALLSTAR INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "BUDGET HOST INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "BUDGETEL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SUISSE CHALETS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CLARION HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "COMPRI HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "COMPRI HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "COURTYARD BY MARRIOTT":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CONSORT HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DILLION INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DOUBLETREE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "DRURY INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ECONOMY INNS OF AMERICA":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "EMBASSY SUITES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "EXEL INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FARFIELD HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HARLEY HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MIDWAY MOTOR LODGE":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MOTEL 6":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "GUEST QUARTERS (Formally PICKETT SUITE HOTELS)":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "THE REGISTRY HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RESIDENCE INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ROYCE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SANDMAN INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SHILO INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SHONEY’S INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SUPER8 MOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "THE RITZ CARLTON HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FLAG INNS (AUSRALIA)":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "GOLDEN CHAIN HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "QUALITY PACIFIC HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FOUR SEASONS HOTEL (AUSTRALIA)":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "FARIFIELD INN":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CARLTON HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CITY LODGE HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "KAROS HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PROTEA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SOUTHERN SUN HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HILTON CONRAD":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "WYNDHAM HOTEL AND RESORTS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RICA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "INER NOR HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SEAINES PLANATION":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RIO SUITES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "BROADMOOR HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "BALLY’S HOTEL AND CASINO":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "JOHN ASCUAGA’S NUGGET":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MGM GRAND HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HARRAH’S HOTELS AND CASINOS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "OPRYLAND HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "BOCA RATON RESORT":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HARVEY/BRISTOL HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "* MASTERS ECONOMY INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "COLORADO BELLE/EDGEWATER RESORT":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "RIVIERA HOTEL AND CASINO":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "TROPICANA RESORT AND CASINO":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "WOODSIDE HOTELS AND RESORTS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "TOWNPLACE SUITES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "MILLENIUM BROADWAY HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CLUB MED":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "BILTMORE HOTEL AND SUITES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CAREFREE RESORTS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "ST. REGIS HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "THE ELIOT HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CLUBCORP/CLUB RESORTS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "WELESLEY INNS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "THE BEVERLY HILLS HOTEL":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "CROWNE PLAZA HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "HOMEWOOD SUITES":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "PEABODY HOTELS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "GREENBRIAH RESORTS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "AMELIA ISLAND PLANATION":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "THE HOMESTEAD":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "SOUTH SEAS RESORTS":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "Local/Suburban Commuter Passenger Transportation – Railroads, Feries, Local Water Transportation.":spendingEmissionsFactorsUKgovGBP["Railway transport"],
    "Passenger Railways":spendingEmissionsFactorsUKgovGBP["Railway transport"],
    "Ambulance Services":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Taxicabs and Limousines":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Bus Lines, Including Charters, Tour Buses":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Tour Buses":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Delivery Services – Local":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Freight Carriers":spendingEmissionsFactorsUKgovGBP["Water transport"],
    "Motor Freight Carriers":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Moving and Storage Companies":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Trucking – Local/Long Distance":spendingEmissionsFactorsUKgovGBP["Road transport"],
    "Courier Services – Air or Ground":spendingEmissionsFactorsUKgovGBP["Air transport"],
    "Fright Forwarders": spendingEmissionsFactorsUKgovGBP["Water transport"],
    "Storage": spendingEmissionsFactorsUKgovGBP["Warehousing and support services for transportation"],
    "Warehousing, Public": spendingEmissionsFactorsUKgovGBP["Warehousing and support services for transportation"],
    "Cruise Lines": spendingEmissionsFactorsUKgovGBP["Water transport"],
    "Steamship Lines": spendingEmissionsFactorsUKgovGBP["Water transport"],
    "Boat Rentals and Leases": spendingEmissionsFactorsUKgovGBP["Water transport"],
    "Marinas, Marine Service, and Supplies": spendingEmissionsFactorsUKgovGBP["Ships and boats"],
    "Airlines, Air Carriers ( not listed elsewhere)": spendingEmissionsFactorsUKgovGBP["Air transport"],
    "Airports, Airport Terminals":spendingEmissionsFactorsUKgovGBP["Food and beverage serving services"],
    "Flying Fields": spendingEmissionsFactorsUKgovGBP["Air transport"],
    "Travel Agencies and Tour Operations": spendingEmissionsFactorsUKgovGBP["Air transport"],
    "Package Tour Operators (For use in Germany only)": spendingEmissionsFactorsUKgovGBP["Air transport"],
    "Toll and Bridge Fees":  spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Transportation Services, Not elsewhere classified)": spendingEmissionsFactorsUKgovGBP["Air transport"],
    "Telecommunications Equipment including telephone sales":  spendingEmissionsFactorsUKgovGBP["Telecommunications services"],
    "Fax services": spendingEmissionsFactorsUKgovGBP["Telecommunications services"],
    "Telecommunication service including local and long distance calls, credit card calls, calls through use of magnetic-strip reading telephones and fax services": spendingEmissionsFactorsUKgovGBP["Telecommunications services"],
    "VisaPhone": spendingEmissionsFactorsUKgovGBP["Telecommunications services"],
    "Telegraph services": spendingEmissionsFactorsUKgovGBP["Telecommunications services"],
    "Money Orders – Wire Transfer":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Cable and other pay television (previously Cable Services)": spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Electric, Gas, Sanitary and Water Utilities":spendingEmissionsFactorsUKgovGBP["Electricity. transmission and distribution"],
    "Motor vehicle supplies and new parts":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Office and Commercial Furniture":spendingEmissionsFactorsUKgovGBP["Services of head offices; management consulting services"],
    "Construction Materials, Not Elsewhere Classified":spendingEmissionsFactorsUKgovGBP["Construction"],
    "Office, Photographic, Photocopy, and Microfilm Equipment":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Computers, Computer Peripheral Equipment, Software": spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Commercial Equipment, Not Elsewhere Classified": spendingEmissionsFactorsUKgovGBP["Electrical equipment"], 
    "Medical, Dental Ophthalmic, Hospital Equipment and Supplies": spendingEmissionsFactorsUKgovGBP["Machinery and equipment n.e.c."],
    "Metal Service Centers and Offices": spendingEmissionsFactorsUKgovGBP["Fabricated metal products. excl. machinery and equipment and weapons & ammunition"],
    "Electrical Parts and Equipment":spendingEmissionsFactorsUKgovGBP["Electrical equipment"],
    "Hardware Equipment and Supplies": spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Plumbing and Heating Equipment and Supplies":spendingEmissionsFactorsUKgovGBP["Natural water; water treatment and supply services"],
    "Industrial Supplies, Not Elsewhere Classified": spendingEmissionsFactorsUKgovGBP["Machinery and equipment n.e.c."], 
    "Precious Stones and Metals, Watches and Jewelry":  spendingEmissionsFactorsUKgovGBP["Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products"],
    "Durable Goods, Not Elsewhere Classified": spendingEmissionsFactorsUKgovGBP["Rubber and plastic products"],
    "Stationery, Office Supplies, Printing, and Writing Paper":spendingEmissionsFactorsUKgovGBP["Paper and paper products"],
    "Drugs, Drug Proprietors, and Druggist’s Sundries": spendingEmissionsFactorsUKgovGBP["Basic pharmaceutical products and pharmaceutical preparations"],
    "Piece Goods, Notions, and Other Dry Goods":spendingEmissionsFactorsUKgovGBP["Textiles"],
    "Men’s Women’s and Children’s Uniforms and Commercial Clothing":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Commercial Footwear":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Chemicals and Allied Products, Not Elsewhere Classified": spendingEmissionsFactorsUKgovGBP["Other chemical products"],
    "Petroleum and Petroleum Products":spendingEmissionsFactorsUKgovGBP["Coke and refined petroleum products"],
    "Books, Periodicals, and Newspapers": spendingEmissionsFactorsUKgovGBP["Paper and paper products"],
    "Florists’ Supplies, Nursery Stock and Flowers": spendingEmissionsFactorsUKgovGBP["Forestry products"],
    "Paints, Varnishes, and Supplies": spendingEmissionsFactorsUKgovGBP["Paints. varnishes and similar coatings. printing ink and mastics"],
    "Non-durable Goods, Not Elsewhere Classified":spendingEmissionsFactorsUKgovGBP["Other manufactured goods"],
    "Home Supply Warehouse Stores": spendingEmissionsFactorsUKgovGBP["Wood and wood products"],
    "Lumber and Building Materials Stores":spendingEmissionsFactorsUKgovGBP["Wood and wood products"],
    "Glass Stores": spendingEmissionsFactorsUKgovGBP["Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products"],
    "Paint and Wallpaper Stores":  spendingEmissionsFactorsUKgovGBP["Paints. varnishes and similar coatings. printing ink and mastics"],
    "Wallpaper Stores": spendingEmissionsFactorsUKgovGBP["Paints. varnishes and similar coatings. printing ink and mastics"],
    "Hardware Stores": spendingEmissionsFactorsUKgovGBP["Fabricated metal products. excl. machinery and equipment and weapons & ammunition"],
    "Nurseries – Lawn and Garden Supply Store": spendingEmissionsFactorsUKgovGBP["Services to buildings and landscape"],
    "Mobile Home Dealers":spendingEmissionsFactorsUKgovGBP["Wholesale and retail trade and repair services of motor vehicles and motorcycles"],
    "Wholesale Clubs": spendingEmissionsFactorsUKgovGBP["Wholesale trade services. except of motor vehicles and motorcycles"],
    "Duty Free Store":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Discount Stores":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Department Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Variety Stores":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Misc. General Merchandise": spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Grocery Stores":emissionsCarbonFootprintOrgGBP["medium meat eater"],
    "Supermarkets":emissionsCarbonFootprintOrgGBP["medium meat eater"],
    "Freezer and Locker Meat Provisioners": spendingEmissionsFactorsUKgovGBP["Preserved meat and meat products"],
    "Meat Provisioners – Freezer and Locker":spendingEmissionsFactorsUKgovGBP["Preserved meat and meat products"],
    "Candy Stores":spendingEmissionsFactorsUKgovGBP["Other food products"],
    "Confectionery Stores":spendingEmissionsFactorsUKgovGBP["Other food products"],
    "Nut Stores":spendingEmissionsFactorsUKgovGBP["Forestry products"],
    "Dairy Products Stores":spendingEmissionsFactorsUKgovGBP["Dairy products"],
    "Bakeries":spendingEmissionsFactorsUKgovGBP["Bakery and farinaceous products"],
    "Misc. Food Stores – Convenience Stores and Specialty Markets":spendingEmissionsFactorsUKgovGBP["Other food products"],
    "Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing":spendingEmissionsFactorsUKgovGBP["Wholesale and retail trade and repair services of motor vehicles and motorcycles"],
    "Automobile and Truck Dealers (Used Only)":spendingEmissionsFactorsUKgovGBP["Wholesale and retail trade and repair services of motor vehicles and motorcycles"],
    "Automobile Supply Stores":spendingEmissionsFactorsUKgovGBP["Wholesale and retail trade and repair services of motor vehicles and motorcycles"],
    "Automotive Tire Stores":spendingEmissionsFactorsUKgovGBP["Rubber and plastic products"],
    "Automotive Parts, Accessories Stores":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Service Stations ( with or without ancillary services)":spendingEmissionsFactorsUKgovGBP["Crude petroleum and natural gas & Metal ores"],
    "Automated Fuel Dispensers":spendingEmissionsFactorsUKgovGBP["Crude petroleum and natural gas & Metal ores"],
    "Boat Dealers":spendingEmissionsFactorsUKgovGBP["Ships and boats"],
    "Recreational and Utility Trailers, Camp Dealers":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Motorcycle Dealers":spendingEmissionsFactorsUKgovGBP["Wholesale and retail trade and repair services of motor vehicles and motorcycles"],
    "Motor Home Dealers":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Snowmobile Dealers":spendingEmissionsFactorsUKgovGBP["Other transport equipment"],
    "Men’s and Boy’s Clothing and Accessories Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Women’s Ready-to-Wear Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Women’s Accessory and Specialty Shops":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Children’s and Infant’s Wear Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Family Clothing Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Sports Apparel, Riding Apparel Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Shoe Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Furriers and Fur Shops":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Men’s and Women’s Clothing Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Tailors, Seamstress, Mending, and Alterations":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Wig and Toupee Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Miscellaneous Apparel and Accessory Shops":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Furniture, Home Furnishings, and Equipment Stores, Except Appliances":spendingEmissionsFactorsUKgovGBP["Furniture"],
    "Floor Covering Stores":spendingEmissionsFactorsUKgovGBP["Manufacture of cement. lime. plaster and articles of concrete. cement and plaster"],
    "Drapery, Window Covering and Upholstery Stores":spendingEmissionsFactorsUKgovGBP["Textiles"],
    "Fireplace, Fireplace Screens, and Accessories Stores":spendingEmissionsFactorsUKgovGBP["Wood and wood products"],
    "Miscellaneous Home Furnishing Specialty Stores":spendingEmissionsFactorsUKgovGBP["Wood and wood products"],
    "Household Appliance Stores":spendingEmissionsFactorsUKgovGBP["Repair services of computers and personal and household goods"],
    "Electronic Sales":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Music Stores, Musical Instruments, Piano Sheet Music": spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Computer Software Stores":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Record Shops": spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Caterers":spendingEmissionsFactorsUKgovGBP["Food and beverage serving services"],
    "Eating places and Restaurants":spendingEmissionsFactorsUKgovGBP["Food and beverage serving services"],
    "Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail lounges, Nightclubs and Discotheques":spendingEmissionsFactorsUKgovGBP["Alcoholic beverages"],
    "Fast Food Restaurants":spendingEmissionsFactorsUKgovGBP["Food and beverage serving services"],
    "Drug Stores and Pharmacies":spendingEmissionsFactorsUKgovGBP["Basic pharmaceutical products and pharmaceutical preparations"],
    "Package Stores – Beer, Wine, and Liquor":spendingEmissionsFactorsUKgovGBP["Wholesale trade services. except of motor vehicles and motorcycles"],
    "Used Merchandise and Secondhand Stores":spendingEmissionsFactorsUKgovGBP["Wholesale trade services. except of motor vehicles and motorcycles"],
    "Antique Shops – Sales, Repairs, and Restoration Services":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Pawn Shops and Salvage Yards":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Wrecking and Salvage Yards":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Antique Reproductions":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Bicycle Shops – Sales and Service":spendingEmissionsFactorsUKgovGBP["Machinery and equipment n.e.c."],
    "Sporting Goods Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Book Stores":spendingEmissionsFactorsUKgovGBP["Printing and recording services"],
    "Stationery Stores, Office and School Supply Stores":spendingEmissionsFactorsUKgovGBP["Printing and recording services"],
    "Watch, Clock, Jewelry, and Silverware Stores":spendingEmissionsFactorsUKgovGBP["Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products"],
    "Hobby, Toy, and Game Shops":spendingEmissionsFactorsUKgovGBP["Rubber and plastic products"],
    "Camera and Photographic Supply Stores":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Card Shops, Gift, Novelty, and Souvenir Shops":spendingEmissionsFactorsUKgovGBP["Paper and paper products"],
    "Leather Foods Stores":spendingEmissionsFactorsUKgovGBP["Leather products"],
    "Sewing, Needle, Fabric, and Price Goods Stores":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Glassware/Crystal Stores":spendingEmissionsFactorsUKgovGBP["Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products"],
    "Direct Marketing- Insurance Service":spendingEmissionsFactorsUKgovGBP["Advertising and market research services"],
    "Mail Order Houses Including Catalog Order Stores, Book/Record Clubs (No longer permitted for U.S. original presentments)":spendingEmissionsFactorsUKgovGBP["Postal and courier services"],
    "Direct Marketing – Travel Related Arrangements Services":spendingEmissionsFactorsUKgovGBP["Insurance. reinsurance and pension funding services. except compulsory social security & Pensions"],
    "Door-to-Door Sales":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Direct Marketing – Catalog Merchant":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Direct Marketing – Catalog and Catalog and Retail Merchant":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Direct Marketing- Outbound Telemarketing Merchant":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Direct Marketing – Inbound Teleservices Merchant":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Direct Marketing – Continuity/Subscription Merchant":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Direct Marketing – Not Elsewhere Classified":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Artist’s Supply and Craft Shops":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Art Dealers and Galleries":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Stamp and Coin Stores – Philatelic and Numismatic Supplies":spendingEmissionsFactorsUKgovGBP["Postal and courier services"],
    "Religious Goods Stores":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Hearing Aids – Sales, Service, and Supply Stores":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Orthopedic Goods Prosthetic Devices":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Cosmetic Stores":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Typewriter Stores – Sales, Rental, Service":spendingEmissionsFactorsUKgovGBP["Machinery and equipment n.e.c."],
    "Fuel – Fuel Oil, Wood, Coal, Liquefied Petroleum":spendingEmissionsFactorsUKgovGBP["Crude petroleum and natural gas & Metal ores"],
    "Florists":spendingEmissionsFactorsUKgovGBP["Forestry products"],
    "Cigar Stores and Stands":spendingEmissionsFactorsUKgovGBP["Tobacco products"],
    "News Dealers and Newsstands":spendingEmissionsFactorsUKgovGBP["Paper and paper products"],
    "Pet Shops, Pet Foods, and Supplies Stores":spendingEmissionsFactorsUKgovGBP["Prepared animal feeds"],
    "Swimming Pools – Sales, Service, and Supplies":spendingEmissionsFactorsUKgovGBP["Natural water; water treatment and supply services"],
    "Electric Razor Stores – Sales and Service":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Tent and Awning Shops":spendingEmissionsFactorsUKgovGBP[  "Retail trade services. except of motor vehicles and motorcycles"],
    "Miscellaneous and Specialty Retail Stores":spendingEmissionsFactorsUKgovGBP[  "Retail trade services. except of motor vehicles and motorcycles"],
    "Financial Institutions – Manual Cash Disbursements":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Financial Institutions – Manual Cash Disbursements":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Financial Institutions – Merchandise and Services":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Non-Financial Institutions – Foreign Currency, Money Orders (not wire transfer) and Travelers Cheques":spendingEmissionsFactorsUKgovGBP[ "Financial services. except insurance and pension funding"],
    "Security Brokers/Dealers":spendingEmissionsFactorsUKgovGBP["Textiles"],
    "Insurance Sales, Underwriting, and Premiums":spendingEmissionsFactorsUKgovGBP["Insurance. reinsurance and pension funding services. except compulsory social security & Pensions"],
    "Insurance Premiums, (no longer valid for first presentment work)":spendingEmissionsFactorsUKgovGBP["Insurance. reinsurance and pension funding services. except compulsory social security & Pensions"],
    "Insurance, Not Elsewhere Classified ( no longer valid for first presentment work)":spendingEmissionsFactorsUKgovGBP["Insurance. reinsurance and pension funding services. except compulsory social security & Pensions"],
    "Lodging – Hotels, Motels, Resorts, Central Reservation Services (not elsewhere classified)":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "Timeshares":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "Sporting and Recreational Camps":spendingEmissionsFactorsUKgovGBP["Sports services and amusement and recreation services"],
    "Trailer Parks and Camp Grounds":spendingEmissionsFactorsUKgovGBP["Accommodation services"],
    "Laundry, Cleaning, and Garment Services":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Laundry – Family and Commercial":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Dry Cleaners":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Carpet and Upholstery Cleaning":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Photographic Studios":spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Barber and Beauty Shops":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Shop Repair Shops and Shoe Shine Parlors, and Hat Cleaning Shops":spendingEmissionsFactorsUKgovGBP["Repair services of computers and personal and household goods"],
    "Funeral Service and Crematories":spendingEmissionsFactorsUKgovGBP["Other personal services"],
    "Dating and Escort Services":spendingEmissionsFactorsUKgovGBP["Other personal services"],
    "Tax Preparation Service":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Counseling Service – Debt, Marriage, Personal":spendingEmissionsFactorsUKgovGBP["Other personal services"],
    "Buying/Shopping Services, Clubs":spendingEmissionsFactorsUKgovGBP["Retail trade services. except of motor vehicles and motorcycles"],
    "Clothing Rental – Costumes, Formal Wear, Uniforms":spendingEmissionsFactorsUKgovGBP["Wearing apparel"],
    "Massage Parlors":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Health and Beauty Shops":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Miscellaneous Personal Services ( not elsewhere classifies)":spendingEmissionsFactorsUKgovGBP["Other personal services"],
    "Advertising Services":spendingEmissionsFactorsUKgovGBP["Advertising and market research services"],
    "Consumer Credit Reporting Agencies":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Blueprinting and Photocopying Services":spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Commercial Photography, Art and Graphics":spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Quick Copy, Reproduction and Blueprinting Services":spendingEmissionsFactorsUKgovGBP["Printing and recording services"],
    "Stenographic and Secretarial Support Services":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Disinfecting Services":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Exterminating and Disinfecting Services":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Cleaning and Maintenance, Janitorial Services":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Employment Agencies, Temporary Help Services":spendingEmissionsFactorsUKgovGBP["Employment services"],
    "Computer Programming, Integrated Systems Design and Data Processing Services":spendingEmissionsFactorsUKgovGBP["Computer programming. consultancy and related services"],
    "Information Retrieval Services":spendingEmissionsFactorsUKgovGBP["Information services"],
    "Computer Maintenance and Repair Services, Not Elsewhere Classified":spendingEmissionsFactorsUKgovGBP["Repair services of computers and personal and household goods"],
    "Management, Consulting, and Public Relations Services":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Protective and Security Services – Including Armored Cars and Guard Dogs":spendingEmissionsFactorsUKgovGBP["Security and investigation services"],
    "Equipment Rental and Leasing Services, Tool Rental, Furniture Rental, and Appliance Rental":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "Photofinishing Laboratories, Photo Developing":spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Business Services, Not Elsewhere Classified":spendingEmissionsFactorsUKgovGBP["Office administrative. office support and other business support services"],
    "Car Rental Companies ( Not Listed Below)":spendingEmissionsFactorsUKgovGBP["Rental and leasing services"],
    "Truck and Utility Trailer Rentals":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Motor Home and Recreational Vehicle Rentals":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Automobile Parking Lots and Garages":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Automotive Body Repair Shops":spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Tire Re-treading and Repair Shops":spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Paint Shops – Automotive":spendingEmissionsFactorsUKgovGBP["Paints. varnishes and similar coatings. printing ink and mastics"],
    "Automotive Service Shops":spendingEmissionsFactorsUKgovGBP["Motor vehicles. trailers and semi-trailers"],
    "Car Washes":spendingEmissionsFactorsUKgovGBP["Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations"],
    "Towing Services":spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Radio Repair Shops":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Air Conditioning and Refrigeration Repair Shops":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Electrical And Small Appliance Repair Shops":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Watch, Clock, and Jewelry Repair":spendingEmissionsFactorsUKgovGBP["Computer. electronic and optical products"],
    "Furniture, Furniture Repair, and Furniture Refinishing":spendingEmissionsFactorsUKgovGBP["Furniture"],
    "Welding Repair":spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Repair Shops and Related Services –Miscellaneous":spendingEmissionsFactorsUKgovGBP["Rest of repair; Installation"],
    "Motion Pictures and Video Tape Production and Distribution":spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Motion Picture Theaters":spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Video Tape Rental Stores":spendingEmissionsFactorsUKgovGBP["Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services"],
    "Dance Halls, Studios and Schools":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Theatrical Producers (Except Motion Pictures), Ticket Agencies":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Billiard and Pool Establishments":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Bowling Alleys":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Commercial Sports, Athletic Fields, Professional Sport Clubs, and Sport Promoters":spendingEmissionsFactorsUKgovGBP["Sports services and amusement and recreation services"],
    "Tourist Attractions and Exhibits":spendingEmissionsFactorsUKgovGBP["Travel agency. tour operator and other reservation services and related services"],
    "Golf Courses – Public":spendingEmissionsFactorsUKgovGBP["Sports services and amusement and recreation services"],
    "Video Amusement Game Supplies":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Video Game Arcades/Establishments":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Betting (including Lottery Tickets, Casino Gaming Chips, Off-track Betting and Wagers)":spendingEmissionsFactorsUKgovGBP["Gambling and betting services"],
    "Amusement Parks, Carnivals, Circuses, Fortune Tellers":spendingEmissionsFactorsUKgovGBP["Creative. arts and entertainment services"],
    "Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses":spendingEmissionsFactorsUKgovGBP["Sports services and amusement and recreation services"],
    "Aquariums, Sea-aquariums, Dolphinariums":spendingEmissionsFactorsUKgovGBP["Sports services and amusement and recreation services"],
    "Recreation Services (Not Elsewhere Classified)":spendingEmissionsFactorsUKgovGBP["Sports services and amusement and recreation services"],
    "Doctors and Physicians (Not Elsewhere Classified)":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Dentists and Orthodontists":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Osteopaths":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Chiropractors":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Optometrists and Ophthalmologists":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Opticians, Opticians Goods and Eyeglasses":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Opticians, Optical Goods, and Eyeglasses (no longer valid for first presentments)":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Podiatrists and Chiropodists":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Nursing and Personal Care Facilities":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Hospitals":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Medical and Dental Laboratories":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Medical Services and Health Practitioners (Not Elsewhere Classified)":spendingEmissionsFactorsUKgovGBP["Human health services"],
    "Legal Services and Attorneys":spendingEmissionsFactorsUKgovGBP["Legal services"],
    "Elementary and Secondary Schools":spendingEmissionsFactorsUKgovGBP["Education services"],
    "Colleges, Junior Colleges, Universities, and Professional Schools":spendingEmissionsFactorsUKgovGBP["Education services"],
    "Correspondence Schools":spendingEmissionsFactorsUKgovGBP["Education services"],
    "Business and Secretarial Schools":spendingEmissionsFactorsUKgovGBP["Education services"],
    "Vocational Schools and Trade Schools":spendingEmissionsFactorsUKgovGBP["Education services"],
    "Schools and Educational Services ( Not Elsewhere Classified)":spendingEmissionsFactorsUKgovGBP["Education services"],
    "Child Care Services":spendingEmissionsFactorsUKgovGBP["Education services"],
    "Charitable and Social Service Organizations":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Civic, Fraternal, and Social Associations":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Political Organizations":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Religious Organizations":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Automobile Associations":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Membership Organizations ( Not Elsewhere Classified)":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Testing Laboratories ( non-medical)":spendingEmissionsFactorsUKgovGBP["Scientific research and development services"],
    "Architectural – Engineering and Surveying Services":spendingEmissionsFactorsUKgovGBP["Scientific research and development services"],
    "Accounting, Auditing, and Bookkeeping Services":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Professional Services ( Not Elsewhere Defined)":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Court Costs, including Alimony and Child Support":spendingEmissionsFactorsUKgovGBP["Legal services"],
    "Fines":spendingEmissionsFactorsUKgovGBP["Legal services"],
    "Bail and Bond Payments":spendingEmissionsFactorsUKgovGBP["Legal services"],
    "Tax Payments":spendingEmissionsFactorsUKgovGBP["Legal services"],
    "Government Services ( Not Elsewhere Classified)":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Postal Services – Government Only":spendingEmissionsFactorsUKgovGBP["Postal and courier services"],
    "Intra – Government Transactions":spendingEmissionsFactorsUKgovGBP["Public administration and defence services; compulsory social security services"],
    "Automated Referral Service ( For Visa Only)":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Visa Credential Service ( For Visa Only)":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "GCAS Emergency Services ( For Visa Only)":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
    "Intra – Company Purchases ( For Visa Only)":spendingEmissionsFactorsUKgovGBP["Financial services. except insurance and pension funding"],
}
module.exports=mccEmissionsFactors