const emissionsCarbonFootprintOrg = require('./emissionsCarbonFootprintOrgGBP');

let plaidCategories = {
              "Bank Fees":emissionsCarbonFootprintOrg["Barely any emissions"],             
              "ATM":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Late Payment":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Fraud Dispute":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Foreign Transaction":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Wire Transfer":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Insufficient Funds":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Excess Activity":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Cash Advance":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Community":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Animal Shelter":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Assisted Living Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Facilities and Nursing Homes":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Caretakers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Cemetery":emissionsCarbonFootprintOrg['Recreational, cultural and sporting activities'],
              "Courts":emissionsCarbonFootprintOrg['Insurance'],
              "Day Care and Preschools":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Disabled Persons Services":emissionsCarbonFootprintOrg['Recreational, cultural and sporting activities'],
              "Drug and Alcohol Services":emissionsCarbonFootprintOrg['Recreational, cultural and sporting activities'],
              "Education":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Vocational Schools":emissionsCarbonFootprintOrg["Education"],
              "Tutoring and Educational Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Primary and Secondary Schools":emissionsCarbonFootprintOrg["Education"],
              "Fraternities and Sororities":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Driving Schools":emissionsCarbonFootprintOrg['Motor vehicles (not including fuel costs)'],
              "Dance Schools":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Culinary Lessons and Schools":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Computer Training":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Colleges and Universities":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Art School":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Adult Education":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Government Departments and Agencies":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Government Lobbyists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Housing Assistance and Shelters":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Law Enforcement":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Police Stations":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Fire Stations":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Correctional Institutions":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Libraries":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Military":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Organizations and Associations":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Youth Organizations":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Environmental":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Charities and Non-Profits":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Post Offices":emissionsCarbonFootprintOrg['Paper based products (e.g. books, magazines, newspapers)'],
              "Public and Social Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Religious":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Temple":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Synagogues":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Mosques":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Churches":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Senior Citizen Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Retirement":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Food and Drink":emissionsCarbonFootprintOrg["medium meat eater"],
              "Bar":emissionsCarbonFootprintOrg["low meat eater"],
              "Wine Bar":emissionsCarbonFootprintOrg["vegetarian"],
              "Sports Bar":emissionsCarbonFootprintOrg["medium meat eater"],
              "Hotel Lounge":emissionsCarbonFootprintOrg["medium meat eater"],
              "Breweries":emissionsCarbonFootprintOrg["medium meat eater"],
              "Internet Cafes":emissionsCarbonFootprintOrg["low meat eater"],
              "Nightlife":emissionsCarbonFootprintOrg["low meat eater"],
              "Strip Club":emissionsCarbonFootprintOrg["vegetarian"],
              "Night Clubs":emissionsCarbonFootprintOrg["vegetarian"],
              "Karaoke":emissionsCarbonFootprintOrg["vegetarian"],
              "Jazz and Blues Cafe":emissionsCarbonFootprintOrg["medium meat eater"],
              "Hookah Lounges":emissionsCarbonFootprintOrg["vegetarian"],
              "Adult Entertainment":emissionsCarbonFootprintOrg["vegetarian"],
              "Restaurants":emissionsCarbonFootprintOrg["medium meat eater"],
              "Winery":emissionsCarbonFootprintOrg["low meat eater"],
              "Vegan and Vegetarian":emissionsCarbonFootprintOrg["vegetarian"],
              "Turkish":emissionsCarbonFootprintOrg["medium meat eater"],
              "Thai":emissionsCarbonFootprintOrg["medium meat eater"],
              "Swiss":emissionsCarbonFootprintOrg["medium meat eater"],
              "Sushi":emissionsCarbonFootprintOrg["medium meat eater"],
              "Steakhouses":emissionsCarbonFootprintOrg["heavy meat eater"],
              "Spanish":emissionsCarbonFootprintOrg["heavy meat eater"],
              "Seafood":emissionsCarbonFootprintOrg["medium meat eater"],
              "Scandinavian":emissionsCarbonFootprintOrg["medium meat eater"],
              "Portuguese":emissionsCarbonFootprintOrg["medium meat eater"],
              "Pizza":emissionsCarbonFootprintOrg["low meat eater"],
              "Moroccan":emissionsCarbonFootprintOrg["medium meat eater"],
              "Middle Eastern":emissionsCarbonFootprintOrg["medium meat eater"],
              "Mexican":emissionsCarbonFootprintOrg["medium meat eater"],
              "Mediterranean":emissionsCarbonFootprintOrg["medium meat eater"],
              "Latin American":emissionsCarbonFootprintOrg["medium meat eater"],
              "Korean":emissionsCarbonFootprintOrg["medium meat eater"],
              "Juice Bar":emissionsCarbonFootprintOrg["vegetarian"],
              "Japanese":emissionsCarbonFootprintOrg["medium meat eater"],
              "Italian": emissionsCarbonFootprintOrg["medium meat eater"],
              "Indonesian":emissionsCarbonFootprintOrg["medium meat eater"],
              "Indian":emissionsCarbonFootprintOrg["medium meat eater"],
              "Ice Cream":emissionsCarbonFootprintOrg["vegetarian"],
              "Greek":emissionsCarbonFootprintOrg["medium meat eater"],
              "German":emissionsCarbonFootprintOrg["medium meat eater"],
              "Gastropub":emissionsCarbonFootprintOrg["medium meat eater"],
              "French":emissionsCarbonFootprintOrg["medium meat eater"],
              "Food Truck":emissionsCarbonFootprintOrg["medium meat eater"],
              "Fish and Chips":emissionsCarbonFootprintOrg["medium meat eater"],
              "Filipino":emissionsCarbonFootprintOrg["medium meat eater"],
              "Fast Food":emissionsCarbonFootprintOrg["heavy meat eater"],
              "Falafel":emissionsCarbonFootprintOrg["low meat eater"],
              "Ethiopian":emissionsCarbonFootprintOrg["medium meat eater"],
              "Eastern European":emissionsCarbonFootprintOrg["medium meat eater"],
              "Donuts":emissionsCarbonFootprintOrg["low meat eater"],
              "Distillery":emissionsCarbonFootprintOrg["vegetarian"],
              "Diners":emissionsCarbonFootprintOrg["medium meat eater"],
              "Dessert":emissionsCarbonFootprintOrg["vegetarian"],
              "Delis":emissionsCarbonFootprintOrg["medium meat eater"],
              "Cupcake Shop":emissionsCarbonFootprintOrg["vegetarian"],
              "Cuban":emissionsCarbonFootprintOrg["medium meat eater"],
              "Coffee Shop":emissionsCarbonFootprintOrg["vegetarian"],
              "Chinese":emissionsCarbonFootprintOrg["medium meat eater"],
              "Caribbean":emissionsCarbonFootprintOrg["medium meat eater"],
              "Cajun":emissionsCarbonFootprintOrg["medium meat eater"],
              "Cafe":emissionsCarbonFootprintOrg["vegetarian"],
              "Burrito":emissionsCarbonFootprintOrg["medium meat eater"],
              "Burgers":emissionsCarbonFootprintOrg["heavy meat eater"],
              "Breakfast Spot":emissionsCarbonFootprintOrg["low meat eater"],
              "Brazilian":emissionsCarbonFootprintOrg["medium meat eater"],
              "Barbecue":emissionsCarbonFootprintOrg["heavy meat eater"],
              "Bakery":emissionsCarbonFootprintOrg["vegetarian"],
              "Bagel Shop":emissionsCarbonFootprintOrg["low meat eater"],
              "Australian":emissionsCarbonFootprintOrg["medium meat eater"],
              "Asian":emissionsCarbonFootprintOrg["medium meat eater"],
              "American":emissionsCarbonFootprintOrg["heavy meat eater"],
              "African":emissionsCarbonFootprintOrg["medium meat eater"],
              "Afghan":emissionsCarbonFootprintOrg["medium meat eater"],
              "Healthcare":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Healthcare Services":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Psychologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Pregnancy and Sexual Health":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Podiatrists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Physical Therapy":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Optometrists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Nutritionists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Nurses":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Mental Health":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Medical Supplies and Labs":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Emergency Services":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Dentists":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Counseling and Therapy":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Chiropractors":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Blood Banks and Centers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Alternative Medicine":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Acupuncture":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Physicians":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Urologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Respiratory":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Radiologists":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Psychiatrists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Plastic Surgeons":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Pediatricians":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Pathologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Orthopedic Surgeons":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Ophthalmologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Oncologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Obstetricians and Gynecologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Neurologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Internal Medicine":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "General Surgery":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Gastroenterologists":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Family Medicine":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Dermatologists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Cardiologists":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Anesthesiologists":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Interest":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Interest Earned":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Interest Charged":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Payment":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Credit Card":emissionsCarbonFootprintOrg["Barely any emissions"],
             
              "Loan":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Recreation":emissionsCarbonFootprintOrg['Recreational, cultural and sporting activities'],
              "Arts and Entertainment":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Theatrical Productions":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Symphony and Opera":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Sports Venues":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Social Clubs":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Psychics and Astrologers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Party Centers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Music and Show Venues":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Museums":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Movie Theatres":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Fairgrounds and Rodeos":emissionsCarbonFootprintOrg["Barely any emissions"],
             
              "Dance Halls and Saloons":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Circuses and Carnivals":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Casinos and Gaming":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Bowling":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Billiards and Pool":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Art Dealers and Galleries":emissionsCarbonFootprintOrg["Barely any emissions"],
            "Arcades and Amusement Parks":emissionsCarbonFootprintOrg['Recreational, cultural and sporting activities'],
              "Aquarium":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Athletic Fields":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Baseball":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Basketball":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Batting Cages":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Boating":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Campgrounds and RV Parks":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Canoes and Kayaks":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Combat Sports":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Cycling":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Dance":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Equestrian":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Football":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Go Carts":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Golf":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Gun Ranges":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Gymnastics":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Gyms and Fitness Centers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Hiking":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Hockey":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Hot Air Balloons":emissionsCarbonFootprintOrg['Recreational, cultural and sporting activities'],
              "Hunting and Fishing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Landmarks":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Monuments and Memorials":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Historic Sites":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Gardens":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Buildings and Structures":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Miniature Golf":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Outdoors":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Rivers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Mountains":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Lakes":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Forests":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Beaches":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Paintball":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Parks":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Playgrounds":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Picnic Areas":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Natural Parks":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Personal Trainers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Race Tracks":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Racquet Sports":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Racquetball":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Rafting":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Recreation Centers":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Rock Climbing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Running":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Scuba Diving":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Skating":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Skydiving":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Snow Sports":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Soccer":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Sports and Recreation Camps":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Sports Clubs":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Stadiums and Arenas":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Swimming":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Tennis":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Water Sports":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Yoga and Pilates":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Zoo":emissionsCarbonFootprintOrg["Recreational, cultural and sporting activities"],
              "Service":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Advertising and Marketing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Search Engine Marketing and Optimization":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Public Relations":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Promotional Items":emissionsCarbonFootprintOrg["Barely any emissions"],
             "Print, TV, Radio and Outdoor Advertising":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Online Advertising":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Market Research and Consulting":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Direct Mail and Email Marketing Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Creative Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Advertising Agencies and Media Buyers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Art Restoration":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Audiovisual":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Automation and Control Systems":emissionsCarbonFootprintOrg["Computers and IT equipment"],
              "Automotive":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Towing":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Maintenance and Repair":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Car Wash and Detail":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Car Appraisers":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Auto Transmission":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Auto Tires":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Auto Smog Check":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Auto Oil and Lube":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Business and Strategy Consulting":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Business Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Printing and Publishing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Cable":emissionsCarbonFootprintOrg["Barely any emissions"],
             
              "Cleaning":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Computers":emissionsCarbonFootprintOrg['Computers and IT equipment'],
              
           
              "Construction":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Specialty":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Roofers":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
            
              "Masonry":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Infrastructure":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Electricians":emissionsCarbonFootprintOrg['Television, radio and phone (equipment)'],
              
            
              "Carpenters":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Credit Counseling and Bankruptcy Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Dating and Escort":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Employment Agencies":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Engineering":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Entertainment":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Media":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Events and Event Planning":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Financial":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Taxes":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Student Aid and Grants":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Stock Brokers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Loans and Mortgages":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Holding and Investment Offices":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Fund Raising":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Financial Planning and Investments":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Credit Reporting":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Collections":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Check Cashing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Business Brokers and Franchises":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Banking and Finance":emissionsCarbonFootprintOrg["Barely any emissions"],
              "ATMs":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Accounting and Bookkeeping":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Food and Beverage":emissionsCarbonFootprintOrg[ "medium meat eater"],
              "Distribution":emissionsCarbonFootprintOrg[ "medium meat eater"],
              "Catering":emissionsCarbonFootprintOrg[ "medium meat eater"],
              "Funeral Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Geological":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Home Improvement":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Upholstery":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Tree Service":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Swimming Pool Maintenance and Services":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Pools and Spas":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Plumbing":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Pest Control":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Painting":emissionsCarbonFootprintOrg['Pharmaceuticals'],
              "Movers":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Mobile Homes":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Lighting Fixtures":emissionsCarbonFootprintOrg["Television, radio and phone (equipment)"],
              "Landscaping and Gardeners":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Kitchens":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Interior Design":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Housewares":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Home Inspection Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Home Appliances":emissionsCarbonFootprintOrg["Television, radio and phone (equipment)"],
              "Hardware and Services":emissionsCarbonFootprintOrg["Television, radio and phone (equipment)"],
              "Doors and Windows":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Contractors":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Carpet and Flooring":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Architects":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Household":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Human Resources":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Immigration":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Import and Export":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Industrial Machinery and Vehicles":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Insurance":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Internet Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Leather":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"]+emissionsCarbonFootprintOrg["heavy meat eater"],
              "Legal":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Logging and Sawmills":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Machine Shops":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Management":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Manufacturing":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Apparel and Fabric Products":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Chemicals and Gasses":emissionsCarbonFootprintOrg["Pharmaceuticals"],
              "Computers and Office Machines":emissionsCarbonFootprintOrg["Computers and IT equipment"],
              "Electrical Equipment and Components":emissionsCarbonFootprintOrg['Television, radio and phone (equipment)'],
              "Furniture and Fixtures":emissionsCarbonFootprintOrg['Furniture and other manufactured goods'],
              "Glass Products":emissionsCarbonFootprintOrg['Furniture and other manufactured goods'],
              "Industrial Machinery and Equipment":emissionsCarbonFootprintOrg['Motor vehicles (not including fuel costs)'],
              "Leather Goods":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"]+emissionsCarbonFootprintOrg["heavy meat eater"],
              "Metal Products":emissionsCarbonFootprintOrg['Furniture and other manufactured goods'],
              "Nonmetallic Mineral Products":emissionsCarbonFootprintOrg['Furniture and other manufactured goods'],
              "Paper Products":emissionsCarbonFootprintOrg['Paper based products (e.g. books, magazines, newspapers)'],
              "Plastic Products":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Rubber Products":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Service Instruments":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Tobacco":emissionsCarbonFootprintOrg["heavy meat eater"],
              "Transportation Equipment":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Wood Products":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Media Production":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Metals":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Mining":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Coal":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Metal":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Non-Metallic Minerals":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "News Reporting":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Oil and Gas":emissionsCarbonFootprintOrg["petrol"],
              "Packaging":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Paper":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Personal Care":emissionsCarbonFootprintOrg["Pharmaceuticals"],
              "Tattooing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Tanning Salons":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Spas":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Skin Care":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Piercing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Massage Clinics and Therapists":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Manicures and Pedicures":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Laundry and Garment Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Hair Salons and Barbers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Hair Removal":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Petroleum":emissionsCarbonFootprintOrg["petrol"],
              "Photography":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Plastics":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Real Estate":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Real Estate Development and Title Companies":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Real Estate Appraiser":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Real Estate Agents":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Property Management":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Corporate Housing":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Commercial Real Estate":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Building and Land Surveyors":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Boarding Houses":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Rent":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Refrigeration and Ice":emissionsCarbonFootprintOrg["heavy meat eater"],
              "Renewable Energy":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Repair Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Research":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Rubber":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Scientific":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Security and Safety":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Shipping and Freight":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Software Development":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Storage":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Subscription":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Tailors":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Telecommunication Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Textiles":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Tourist Information and Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Transportation":emissionsCarbonFootprintOrg["train"],
              "Travel Agents and Tour Operators":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Utilities":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Water":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Sanitary and Waste Management":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Gas":emissionsCarbonFootprintOrg["petrol"],
              "Electric":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Veterinarians":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Water and Waste Management":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Web Design and Development":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Welding":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Agriculture and Forestry":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Crop Production":emissionsCarbonFootprintOrg["vegan"],
              "Forestry":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Livestock and Animals":emissionsCarbonFootprintOrg["low meat eater"],
              "Services":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Art and Graphic Design":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Shops":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Adult":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Antiques":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Arts and Crafts":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Auctions":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Used Car Dealers":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Salvage Yards":emissionsCarbonFootprintOrg["Barely any emissions"],
              "RVs and Motor Homes":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Classic and Antique Car":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Car Parts and Accessories":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Car Dealers and Leasing":emissionsCarbonFootprintOrg["Motor vehicles (not including fuel costs)"],
              "Beauty Products":emissionsCarbonFootprintOrg["Pharmaceuticals"],
              "Bicycles":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Boat Dealers":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Bookstores":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Cards and Stationery":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Children":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Clothing and Accessories":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Women's Store":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Computers and Electronics":emissionsCarbonFootprintOrg["Computers and IT equipment"],
              "Video Games":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Mobile Phones":emissionsCarbonFootprintOrg["Computers and IT equipment"],
              "Cameras":emissionsCarbonFootprintOrg["Computers and IT equipment"],
              "Construction Supplies":emissionsCarbonFootprintOrg['Furniture and other manufactured goods'],
              "Convenience Stores":emissionsCarbonFootprintOrg["medium meat eater"],
              "Costumes":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Dance and Music":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Department Stores":emissionsCarbonFootprintOrg['Clothes, textiles and shoes'],
              "Digital Purchase":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Discount Stores":emissionsCarbonFootprintOrg['Clothes, textiles and shoes'],
              "Electrical Equipment":emissionsCarbonFootprintOrg["Computers and IT equipment"],
              "Equipment Rental":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Flea Markets":emissionsCarbonFootprintOrg['Clothes, textiles and shoes'],
              "Florists":emissionsCarbonFootprintOrg['vegan'],
              "Food and Beverage Store":emissionsCarbonFootprintOrg["low meat eater"],
              "Health Food":emissionsCarbonFootprintOrg["low meat eater"],
              "Farmers Markets":emissionsCarbonFootprintOrg["low meat eater"],
              "Fuel Dealer":emissionsCarbonFootprintOrg["petrol"],
              "Furniture and Home Decor":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Gift and Novelty":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Glasses and Optometrist":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Hardware Store":emissionsCarbonFootprintOrg["Television, radio and phone (equipment)"],
              "Hobby and Collectibles":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Industrial Supplies":emissionsCarbonFootprintOrg["Television, radio and phone (equipment)"],
              "Jewelry and Watches":emissionsCarbonFootprintOrg["Television, radio and phone (equipment)"],
              "Luggage":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Marine Supplies":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Musical Instruments":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Newsstands":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Office Supplies":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Outlet":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Swimwear":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Shoe Store":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Men's Store":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Lingerie Store":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Kids' Store":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Boutique":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Accessories Store":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Pawn Shops":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Pets":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Pharmacies":emissionsCarbonFootprintOrg["Pharmaceuticals"],
              "Photos and Frames":emissionsCarbonFootprintOrg["Paper based products (e.g. books, magazines, newspapers)"],
              "Shopping Centers and Malls":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Sporting Goods":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Supermarkets and Groceries":emissionsCarbonFootprintOrg["medium meat eater"],
              "Toys":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Vintage and Thrift":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Warehouses and Wholesale Stores":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Wedding and Bridal":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Wholesale":emissionsCarbonFootprintOrg["Clothes, textiles and shoes"],
              "Lawn and Garden":emissionsCarbonFootprintOrg["Furniture and other manufactured goods"],
              "Tax":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Refund":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Transfer":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Internal Account Transfer":emissionsCarbonFootprintOrg["Barely any emissions"],
              "ACH":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Billpay":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Credit":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Debit":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Deposit":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Check":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Keep the Change Savings Program":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Payroll":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Benefits":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Third Party":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Venmo":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Square Cash":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Square":emissionsCarbonFootprintOrg["Barely any emissions"],
              "PayPal":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Dwolla":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Coinbase":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Chase QuickPay":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Acorns":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Digit":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Betterment":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Plaid":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Wire":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Withdrawal":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Save As You Go":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Travel":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Airlines and Aviation Services":emissionsCarbonFootprintOrg['flights'],
              "Airports":emissionsCarbonFootprintOrg['heavy meat eater'],
              "Boat":emissionsCarbonFootprintOrg['train'],
              "Bus Stations":emissionsCarbonFootprintOrg['train'],              
              "Car and Truck Rentals":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Car Service":emissionsCarbonFootprintOrg['car'],
              "Ride Share":emissionsCarbonFootprintOrg['car'],
              "Charter Buses":emissionsCarbonFootprintOrg['train'],
              "Cruises":emissionsCarbonFootprintOrg['flights'],
              "Gas Stations":emissionsCarbonFootprintOrg['petrol'],
              "Heliports":emissionsCarbonFootprintOrg['flights'],
              "Limos and Chauffeurs":emissionsCarbonFootprintOrg['car'],
              "Lodging":emissionsCarbonFootprintOrg["Hotels, restaurants, and pubs etc."],
              "Resorts":emissionsCarbonFootprintOrg["Hotels, restaurants, and pubs etc."],
              "Lodges and Vacation Rentals":emissionsCarbonFootprintOrg["Hotels, restaurants, and pubs etc."],
              "Hotels and Motels":emissionsCarbonFootprintOrg["Hotels, restaurants, and pubs etc."],
              "Hostels":emissionsCarbonFootprintOrg["Hotels, restaurants, and pubs etc."],
              "Cottages and Cabins":emissionsCarbonFootprintOrg["Hotels, restaurants, and pubs etc."],
              "Bed and Breakfasts":emissionsCarbonFootprintOrg["Hotels, restaurants, and pubs etc."],
              "Parking":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Public Transportation Services":emissionsCarbonFootprintOrg['train'],
              "Rail":emissionsCarbonFootprintOrg['train'],
              "Taxi":emissionsCarbonFootprintOrg['car'],
              "Tolls and Fees":emissionsCarbonFootprintOrg["Barely any emissions"],
              "Transportation Centers":emissionsCarbonFootprintOrg["Barely any emissions"],          
            }

            module.exports = plaidCategories;