const spendingEmissionsFactorsUKgovGBP = {
    "Agriculture products":3.10,
    "Forestry products":0.75,
    "Fish products":0.93,
    "Coal. lignite. peat":2.97,
    "Crude petroleum and natural gas & Metal ores":0.66,
    "Other mining and quarrying products":0.81,
    "Mining support services":0.24,
    "Preserved meat and meat products":1.40,
    "Processed and preserved fish. crustaceans. molluscs. fruit and vegetables":0.97,
    "Vegetable and animal oils and fats":0.99,
    "Dairy products":1.82,
    "Grain mill products. starches and starch products":1.33,
    "Bakery and farinaceous products":0.78,
    "Other food products":0.96,
    "Prepared animal feeds":1.27,
    "Alcoholic beverages":0.74,
    "Soft drinks":0.60,
    "Tobacco products":0.56,
    "Textiles":0.96,
    "Wearing apparel":0.68,
    "Leather products":0.54,
    "Wood and wood products":1.02,
    "Paper and paper products":1.18,
    "Printing and recording services":0.58,
    "Coke and refined petroleum products":1.69,
    "Industrial gases. inorganics and fertilisers (all inorganic chemicals)":0.72,
    "Petrochemicals":0.69,
    "Dyestuffs. agro-chemicals":1.02,
    "Paints. varnishes and similar coatings. printing ink and mastics":1.66,
    "Soap and detergents. cleaning and polishing preparations. perfumes and toilet preparations":1.44,
    "Other chemical products":1.57,
    "Basic pharmaceutical products and pharmaceutical preparations":0.35,
    "Rubber and plastic products":0.96,
    "Glass. refractory. clay. other porcelain and ceramic. stone and abrasive products":2.19,
    "Manufacture of cement. lime. plaster and articles of concrete. cement and plaster":1.27,
    "Basic iron and steel":2.59,
    "Other basic metals and casting":1.56,
    "Fabricated metal products. excl. machinery and equipment and weapons & ammunition":0.57,
    "Weapons and ammunition":0.68,
    "Computer. electronic and optical products":0.41,
    "Electrical equipment":0.62,
    "Machinery and equipment n.e.c.":0.56,
    "Motor vehicles. trailers and semi-trailers":0.62,
    "Ships and boats":0.76,
    "Air and spacecraft and related machinery":0.59,
    "Other transport equipment":0.49,
    "Furniture":0.64,
    "Other manufactured goods":0.45,
    "Repair and maintenance of ships and boats":0.69,
    "Repair and maintenance of aircraft and spacecraft":0.56,
    "Rest of repair; Installation":0.41,
    "Electricity. transmission and distribution":3.62,
    "Gas distribution":2.01,
    "Natural water; water treatment and supply services":0.57,
    "Sewerage services; sewage sludge":0.81,
    "Waste collection. treatment and disposal services; materials recovery services":1.36,
    "Remediation services and other waste management services":0.27,
    "Construction":0.37,
    "Wholesale and retail trade and repair services of motor vehicles and motorcycles":0.30,
    "Wholesale trade services. except of motor vehicles and motorcycles":0.35,
    "Retail trade services. except of motor vehicles and motorcycles":0.31,
    "Railway transport":0.56,
    "Road transport":0.78,
    "Water transport":1.90,
    "Air transport":3.00,
    "Warehousing and support services for transportation":0.28,
    "Postal and courier services":0.35,
    "Accommodation services":0.45,
    "Food and beverage serving services":0.40,
    "Publishing services":0.23,
    "Motion picture. video and TV programme production services. sound recording & music publishing & programming and broadcasting services":0.22,
    "Telecommunications services":0.32,
    "Computer programming. consultancy and related services":0.18,
    "Information services":0.18,
    "Financial services. except insurance and pension funding":0.15,
    "Insurance. reinsurance and pension funding services. except compulsory social security & Pensions":0.18,
    "Services auxiliary to financial services and insurance services":0.15,
    "Real estate services. excluding on a fee or contract basis and imputed rent":0.13,
    "Owner-Occupiers' Housing Services":0.11,
    "Real estate services on a fee or contract basis":0.09,
    "Legal services":0.10,
    "Accounting. bookkeeping and auditing services; tax consulting services":0.12,
    "Services of head offices; management consulting services":0.17,
    "Architectural and engineering services; technical testing and analysis services":0.18,
    "Scientific research and development services":0.24,
    "Advertising and market research services":0.20,
    "Other professional. scientific and technical services":0.16,
    "Veterinary services":0.20,
    "Rental and leasing services":0.23,
    "Employment services":0.14,
    "Travel agency. tour operator and other reservation services and related services":0.16,
    "Security and investigation services":0.24,
    "Services to buildings and landscape":0.25,
    "Office administrative. office support and other business support services":0.18,
    "Public administration and defence services; compulsory social security services":0.27,
    "Education services":0.17,
    "Human health services":0.25,
    "Social care services":0.29,
    "Creative. arts and entertainment services":0.24,
    "Libraries. archives. museums and other cultural services":0.25,
    "Gambling and betting services":0.17,
    "Sports services and amusement and recreation services":0.29,
    "Services furnished by membership organisations":0.15,
    "Repair services of computers and personal and household goods":0.22,
    "Other personal services":0.27,
    "Services of households as employers of domestic personnel":0.04,
}

module.exports = spendingEmissionsFactorsUKgovGBP